export const data = [
    {
        "id": "0",
        "title": "Pomegranate",
        "savpercent": "14",
        "listprice": "180",
        "sellprice": "155",
        "image": "anaar.jpg",
        "total": "155",
        "type": "fruits",
        "quantity": "1",
        "quantity1": "1",
        "initialquant":"1",
        "measure": "kg"
    },
    {
        "id": "1",
        "title": "Apple",
        "savpercent": "10",
        "listprice": "145",
        "sellprice": "130",
        "image": "apple.jpg",
        "total": "145",
        "type": "fruits",
        "quantity": "1",
        "quantity1": "1",
        "initialquant":"1",
        "measure": "kg"
    },
    {
        "id": "2",
        "title": "PineApple",
        "savpercent": "13",
        "listprice": "90",
        "sellprice": "78",
        "image": "pineapple.jpg",
        "total": "78",
        "type": "fruits",
        "quantity": "1",
        "quantity1": "1",
        "initialquant":"1",
        "measure": "unit"
    },
    {
        "id": "3",
        "title": "Kiwi",
        "savpercent": "17",
        "listprice": "120",
        "sellprice": "100",
        "image": "kiwi.jpg",
        "total": "100",
        "type": "fruits",
        "quantity": "3",
        "quantity1": "3",
        "initialquant":"3",
        "measure": "unit"
    },
    {
        "id": "4",
        "title": "Guava",
        "savpercent": "8",
        "listprice": "65",
        "sellprice": "60",
        "image": "Guava.jpg",
        "total": "60",
        "type": "fruits",
        "quantity": "1",
        "quantity1": "1",
        "initialquant":"1",
        "measure": "kg"
    },
    {
        "id": "5",
        "title": "Banana",
        "savpercent": "17",
        "listprice": "60",
        "sellprice": "50",
        "image": "banana.jpg",
        "total": "50",
        "type": "fruits",
        "quantity": "6",
        "quantity1": "6",
        "initialquant":"6",
        "measure": "unit"
    },
    {
        "id": "6",
        "title": "Papaya",
        "savpercent": "8",
        "listprice": "60",
        "sellprice": "55",
        "image": "papaya.jpg",
        "total": "55",
        "type": "fruits",
        "quantity": "1",
        "quantity1": "1",
        "initialquant":"1",
        "measure": "unit"
    },
    {
        "id": "7",
        "title": "Mosammi",
        "savpercent": "8",
        "listprice": "60",
        "sellprice": "50",
        "image": "mosammi.jpg",
        "total": "50",
        "type": "fruits",
        "quantity": "1",
        "quantity1": "1",
        "initialquant":"1",
        "measure": "kg"
    },
    {
        "id": "8",
        "title": "Watermelon",
        "savpercent": "9",
        "listprice": "110",
        "sellprice": "100",
        "image": "watermelon.jpg",
        "total": "100",
        "type": "fruits",
        "quantity": "1",
        "quantity1": "1",
        "initialquant":"1",
        "measure": "unit"
    },
    {
        "id": "9",
        "title": "Pear",
        "savpercent": "7",
        "listprice": "150",
        "sellprice": "140",
        "image": "pear.jpg",
        "total": "140",
        "type": "fruits",
        "quantity": "1/2",
        "quantity1": "1/2",
        "initialquant":"1/2",
        "measure": "kg"
    },
    {
        "id": "10",
        "title": "Tomato",
        "savpercent": "14",
        "listprice": "60",
        "sellprice": "50",
        "image": "tamato.jpg",
        "total": "50",
        "type": "vegetables",
        "quantity": "1",
        "quantity1": "1",
        "initialquant":"1",
        "measure": "kg"
    },
    {
        "id": "11",
        "title": "Potato",
        "savpercent": "33",
        "listprice": "35",
        "sellprice": "20",
        "image": "potato.jpg",
        "total": "20",
        "type": "vegetables",
        "quantity": "1",
        "quantity1": "1",
        "initialquant":"1",
        "measure": "kg"
    },
    {
        "id": "12",
        "title": "Onion",
        "savpercent": "40",
        "listprice": "50",
        "sellprice": "30",
        "image": "onion.jpg",
        "total": "30",
        "type": "vegetables",
        "quantity": "1",
        "quantity1": "1",
        "initialquant":"1",
        "measure": "kg"
    },
    {
        "id": "13",
        "title": "Large round Brinjal",
        "savpercent": "33",
        "listprice": "30",
        "sellprice": "20",
        "image": "bharta.jpg",
        "total": "100",
        "type": "vegetables",
        "quantity": "1/2",
        "quantity1": "1/2",
        "initialquant":"1/2",
        "measure": "kg"
    },
    {
        "id": "14",
        "title": "Long brinjal",
        "savpercent": "43",
        "listprice": "35",
        "sellprice": "20",
        "image": "longbrinjal.jpg",
        "total": "20",
        "type": "vegetables",
        "quantity": "1/2",
        "quantity1": "1/2",
        "initialquant":"1/2",
        "measure": "kg"
    },
    {
        "id": "15",
        "title": "Lady Finger",
        "savpercent": "33",
        "listprice": "60",
        "sellprice": "40",
        "image": "ladyfinger.jpg",
        "total": "40",
        "type": "vegetables",
        "quantity": "1/2",
        "quantity1": "1/2",
        "initialquant":"1/2",
        "measure": "kg"
    },
    {
        "id": "16",
        "title": "Green chilli",
        "savpercent": "25",
        "listprice": "20",
        "sellprice": "15",
        "image": "greenchilli.jpg",
        "total": "15",
        "type": "vegetables",
        "quantity": "250",
        "quantity1": "250",
        "initialquant":"250",
        "measure": "gm"
    },
    {
        "id": "17",
        "title": "Ginger",
        "savpercent": "33",
        "listprice": "30",
        "sellprice": "20",
        "image": "ginger.jpg",
        "total": "20",
        "type": "vegetables",
        "quantity": "250",
        "quantity1": "250",
        "initialquant":"250",
        "measure": "gm"
    },
    {
        "id": "18",
        "title": "Capsicum",
        "savpercent": "50",
        "listprice": "40",
        "sellprice": "20",
        "image": "capsicum.jpg",
        "total": "20",
        "type": "vegetables",
        "quantity": "250",
        "quantity1": "250",
        "initialquant":"250",
        "measure": "gm"
    },
    {
        "id": "19",
        "title": "Carrot",
        "savpercent": "33",
        "listprice": "30",
        "sellprice": "20",
        "image": "carrot.jpg",
        "total": "140",
        "type": "vegetables",
        "quantity": "1/2",
        "quantity1": "1/2",
        "initialquant":"1/2",
        "measure": "kg"
    }
]
